name: Docker Image CI

on:
  push:
    paths:
     - "app/**"
     - "requirements.txt"
  #   branches: [ "master" ]
  #   tags: ["v*.*,*"]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
  PUSH_GHCR: "false"

jobs:
  docker:
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,branch=main,name=latest
          type=ref,event=branch,enable=true
          type=ref,event=tag
          type=sha
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.run_id }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64, linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ steps.cache.outputs.cache_from }}
        cache-to: ${{ steps.cache.outputs.cache_to }}
  
